### ISSUE TITLE
About worflow

### ISSUE THREAD

**Issue by kudashevs** [spatie/cpu-load-health-check#17]
Hello,

I have one question about this package's github workflow. Do we need a [support for Laravel 9 here](https://github.com/spatie/cpu-load-health-check/blob/c7d581c9718636e3ae4063972932a7dd2bb860ca/.github/workflows/run-tests.yml#L17)?

There is a discrepancy with another [heath check package](https://github.com/spatie/security-advisories-health-check/blob/de0974929d712a8baf3480957686d26245ddcd74/.github/workflows/run-tests.yml#L17). However, the main package tests [both framework versions](https://github.com/spatie/laravel-health/blob/ab46a9570811c58c7b4abb1363f58180f0b34c2e/.github/workflows/run-tests.yml#L13).
I can bring both (security advisories and cpu load) package workflows into line with the main package if you don't mind.

**Comment by freekmurze** [comment]
I don't have a hard opinion on this. If the current tests run on L8 I'm ok with it 👍
